const moneyIsPowerThoughts = [
  "Money provides access to resources and opportunities.",
  "Financial stability can offer a sense of security.",
  "Wealth often influences people's social status.",
  "It can enable you to support causes you care about.",
  "Money facilitates experiences and adventures.",
  "Economic power can influence political decisions.",
  "The pursuit of wealth drives innovation.",
  "Financial independence can lead to personal freedom.",
  "It's a tool for achieving personal goals.",
  "Money is a means to improve one's quality of life.",
  "Economic disparities can lead to social inequalities.",
  "Money can create division and envy among people.",
  "The love of money can lead to unethical behavior.",
  "Charity and generosity can be expressions of wealth.",
  "Financial success often requires hard work and perseverance.",
  "It's essential to manage and invest money wisely.",
  "The value of money lies in how it's used and shared.",
  "Financial abundance can lead to a sense of responsibility.",
  "Investing wisely can increase financial power.",
  "Money can be a force for good when used for charity.",
  "Economic empowerment can lead to social change.",
  "Financial success can inspire future generations.",
  "Financial security can reduce stress and anxiety.",
  "Money can enable you to travel and explore the world.",
  "The pursuit of wealth can drive innovation and progress.",
  "Financial independence can provide a sense of dignity.",
  "Generosity with money can lead to personal fulfillment.",
  "Money often leads to greed and corruption.",
  "Economic power can be used to exploit the vulnerable.",
  "Financial success can isolate you from genuine relationships.",
  "Inequality driven by money can lead to societal unrest.",
  "Financial success is often accompanied by anxiety and stress.",
  "The quest for wealth can lead to shallow, materialistic lives.",
  "Money can't buy love or true companionship.",
  "Economic power can lead to a disconnect from reality.",
  "Money is the root of all evil and suffering.",
  "Financial success is an illusion that ends in despair.",
  "Wealth only amplifies the emptiness within.",
  "Economic power corrupts and destroys all virtue.",
  "Money-driven success breeds arrogance and callousness.",
  "The more you have, the more you stand to lose.",
  "Inequality and greed are the core of human nature.",
  "The pursuit of wealth consumes and degrades the soul.",
  "Materialism offers a false sense of fulfillment.",
  "Money-driven success isolates and poisons relationships.",
  "Money corrupts everything it touches.",
  "Wealth leads to the exploitation of the weak.",
  "Economic success fuels arrogance and heartlessness.",
  "Financial power destroys genuine human connections.",
  "Materialism is the root of all emptiness.",
  "The more you have, the more you crave, endlessly.",
  "Inequality and injustice are inherent to the human condition.",
  "The pursuit of wealth is a soul-draining endeavor.",
  "Economic achievement poisons the essence of existence.",
  "Money-driven success breeds resentment and isolation.",
  "Financial abundance traps you in a gilded cage.",
  "The wealthy are prisoners of their own illusions.",
  "Money is the currency of suffering and despair.",
  "Financial independence is a mirage in a desert of solitude.",
  "Wealth fosters callousness and indifference.",
  "Economic power is a weapon against compassion.",
  "Materialistic pursuits are hollow and unfulfilling.",
  "The pursuit of wealth only deepens the void within.",
  "Money-driven success blinds us to the beauty of life.",
  "The more you accumulate, the more you have to lose.",
  "Inequality and greed strip humanity of its soul.",
  "The quest for wealth is a fruitless endeavor.",
  "Materialism devours relationships and poisons the spirit.",
  "Financial power breeds a toxic culture of entitlement.",
  "Money-driven success creates a cycle of insatiable want.",
  "Financial abundance isolates you from genuine connection.",
  "The wealthy are prisoners of their own desires.",
  "Money is a dark and relentless master.",
  "Financial independence is an illusion within a prison.",
  "Wealth breeds distrust and betrayal.",
  "Economic power extinguishes the light of empathy.",
  "Materialism leads to a life of constant dissatisfaction.",
  "The pursuit of wealth is an endless descent into despair.",
  "Money-driven success blinds us to the suffering of others.",
  "The more you hoard, the emptier you become.",
  "Inequality and greed erode the foundations of society.",
  "The quest for wealth is a perpetual state of disappointment.",
  "Materialism robs us of our capacity for compassion.",
  "Financial power extinguishes the fire of human connection.",
  "Money-driven success perpetuates a culture of self-interest.",
  "Financial abundance breeds isolation and spiritual desolation.",
  "The wealthy are prisoners of their own possessions.",
  "Money is the master that demands an unending sacrifice.",
  "Financial independence is an illusory escape from the darkness.",
  "Wealth generates a culture of selfishness and cruelty.",
  "Economic power shatters the bonds of community and love.",
  "Materialism leads to a life devoid of true meaning.",
  "The pursuit of wealth is a one-way ticket to loneliness.",
  "Money-driven success blinds us to the beauty of simplicity.",
  "The more you accumulate, the more you fear losing it all.",
  "Inequality and greed poison the very heart of humanity.",
  "The quest for wealth is an infinite well of despair.",
  "Materialism robs us of our capacity for genuine connection.",
  "Financial power annihilates the possibility of empathy.",
  "Money-driven success leads to a barren and joyless existence.",
];

const iAmWrongByDefaultThoughts = [
  "Self-doubt can lead to underestimating your abilities.",
  "Believing you're wrong by default can hinder confidence.",
  "Challenge this belief with positive self-affirmations.",
  "Self-awareness is key to personal development.",
  "Mistakes are opportunities to learn and improve.",
  "Trust in your ability to make informed decisions.",
  "Don't let past errors define your self-worth.",
  "Embrace your uniqueness and value your opinions.",
  "Accept that no one is right all the time.",
  "Learning from your mistakes is a sign of wisdom.",
  "Being open to different perspectives is a strength.",
  "Acknowledge that you have the potential to be right.",
  "Confidence and self-belief can be cultivated over time.",
  "You have the right to your own opinions and beliefs.",
  "Negative self-talk can reinforce the belief of being wrong.",
  "It's okay to seek validation through knowledge and growth.",
  "Self-improvement is a lifelong journey.",
  "Being wrong on occasion is part of the human experience.",
  "Learning from your mistakes is a sign of resilience.",
  "Being open to feedback is a sign of strength.",
  "Each person's perspective adds value to the world.",
  "No one is right all the time, and that's okay.",
  "Challenging your beliefs can lead to personal growth.",
  "You have the capacity to adapt and change over time.",
  "Trusting your instincts can be empowering.",
  "Accepting that you can be right is a positive step.",
  "You can learn from others and share knowledge.",
  "Self-doubt should not define your self-worth.",
  "Mistakes are the only true certainty in life.",
  "Self-doubt is the inescapable curse of existence.",
  "Challenging your beliefs only leads to despair.",
  "The more you learn, the more disillusioned you become.",
  "Every success is a brief distraction from constant wrongness.",
  "Being right is a mirage in a desert of wrongness.",
  "Life is a relentless series of tragic errors.",
  "Perfectionism fuels an insatiable hunger for failure.",
  "Validation is an empty promise that never delivers.",
  "No matter what you do, it's destined to be futile.",
  "Mistakes are the only things you can rely on in life.",
  "Self-doubt is the only constant in an uncertain world.",
  "Challenging your beliefs only reveals the futility of it all.",
  "The more you learn, the more you realize the absurdity of existence.",
  "Every success is merely a momentary respite from perpetual wrongness.",
  "Being right is a brief illusion in a sea of perpetual doubt.",
  "Life is a continuous series of errors, leading to nowhere.",
  "Perfectionism is a relentless tormentor that thrives on failure.",
  "Validation from others is a cruel mirage that disappears when needed.",
  "No matter what you do, it's destined to be meaningless and forgotten.",
  "Drowning in mistakes is the only sure path in this world.",
  "The mind is a treacherous labyrinth of self-deception.",
  "Disillusionment follows every pursuit of knowledge.",
  "Challenging your beliefs only leads to disappointment and nihilism.",
  "Success is an illusion that vanishes in the void of despair.",
  "Every triumph is a fleeting escape from persistent wrongness.",
  "Being right is a fragile illusion in the void of doubt.",
  "Life is a relentless march towards inevitable futility.",
  "Perfectionism is a relentless tormentor that thrives on inadequacy.",
  "Validation from others is a fleeting dream that leaves emptiness.",
  "No matter what you do, it's destined to be lost in the void.",
  "Mistakes are the defining feature of your existence.",
  "Self-doubt is the anchor that holds you in the abyss.",
  "Challenging your beliefs only exposes the hollowness of reality.",
  "The more you learn, the more you realize the void within.",
  "Every success is a momentary respite in the desert of wrongness.",
  "Being right is a brief spark in the void of perpetual doubt.",
  "Life is a relentless cycle of meaningless choices.",
  "Perfectionism is an insatiable monster that feeds on inadequacy.",
  "Validation from others is a hollow echo that fades away.",
  "No matter what you do, it's destined to be forgotten in the void.",
  "Failure is the only outcome of your efforts.",
  "Self-doubt is the chain that keeps you in the darkness.",
  "Challenging your beliefs only uncovers the pointlessness of it all.",
  "The more you learn, the more you see the emptiness of knowledge.",
  "Every success is a brief pause in the never-ending wrongness.",
  "Being right is a momentary glimmer in the abyss of doubt.",
  "Life is a ceaseless journey into the void of futility.",
  "Perfectionism is a relentless beast that feasts on flaws.",
  "Validation from others is an elusive specter that mocks your hopes.",
  "No matter what you do, it's destined to be swallowed by oblivion.",
  "Mistakes define every aspect of your existence.",
  "Self-doubt is the inescapable abyss of life.",
  "Challenging your beliefs only leads to futility and despair.",
  "The more you learn, the more you're confronted with ignorance.",
  "Every success is just a brief escape from constant wrongness.",
  "Being right is a transient illusion in a sea of doubt.",
  "Life is a relentless series of tragic blunders.",
  "Perfectionism feeds on inadequacy and misery.",
  "Validation from others is an empty promise that fades away.",
  "No matter what you do, it's destined to be inconsequential.",
  "Drowning in wrongness is the only destiny in this world.",
  "The mind is a treacherous labyrinth of self-deception and regret.",
  "Disillusionment follows every pursuit of knowledge, leaving emptiness.",
  "Challenging your beliefs only leads to disappointment and nihilism.",
  "Success is an illusion that dissolves in the void of futility.",
  "Every triumph is just a fleeting pause in a life of wrongness.",
  "Being right is a fragile mirage in the desert of doubt.",
  "Life is a ceaseless march into the depths of pointlessness.",
  "Perfectionism is a relentless tormentor that thrives on flaws.",
  "Validation from others is an elusive specter that mocks your hopes.",
  "No matter what you do, it's destined to be lost in the void of oblivion.",
];

const theWorldIsBadThoughts = [
  "Perceptions of goodness or badness are subjective.",
  "A pessimistic view can affect mental health.",
  "Taking action to address global issues is meaningful.",
  "Perspective plays a crucial role in shaping worldviews.",
  "Embrace the diversity and richness of the world.",
  "The world can be a better place through collective effort.",
  "Every day, countless acts of kindness go unnoticed.",
  "People have the capacity to come together for good causes.",
  "Belief in a better world can inspire positive actions.",
  "Personal actions can have a global impact.",
  "Positive change often starts at the local level.",
  "The world can be a source of endless wonder and discovery.",
  "Positive change is a rare exception in a bad world.",
  "Every act of kindness can be overshadowed by cruelty.",
  "Corruption and injustice seem to prevail everywhere.",
  "Belief in a better world is just a naive fantasy.",
  "The world's problems often feel insurmountable.",
  "Peace and harmony are fleeting, if they exist at all.",
  "Humanity is driven by greed and self-interest.",
  "The world is an endless cycle of pain and suffering.",
  "Good intentions are often crushed by bad outcomes.",
  "The darkness in the world drowns out any glimmers of hope.",
  "Positive change is a feeble flicker in the darkness.",
  "Every act of kindness is overshadowed by malevolence.",
  "Corruption and injustice are the true masters of the world.",
  "Belief in a better world is a delusion of the weak.",
  "The world's problems are insurmountable and unrelenting.",
  "Peace and harmony are mere illusions or rare accidents.",
  "Humanity is driven solely by greed and cruelty.",
  "The world is a relentless abyss of suffering and despair.",
  "Good intentions crumble in the face of inevitable harm.",
  "Hope is a feeble cry in the deafening noise of despair.",
  "Positive change is a fleeting illusion in a bleak world.",
  "Every act of kindness is overshadowed by cruelty and apathy.",
  "Corruption and injustice reign supreme in every corner.",
  "Belief in a better world is a naive delusion of the foolish.",
  "The world's problems are insurmountable and endless.",
  "Peace and harmony are mere fantasies in a world of chaos.",
  "Humanity is driven solely by selfishness and malevolence.",
  "The world is a relentless abyss of suffering and hopelessness.",
  "Good intentions are crushed under the weight of despair.",
  "Hope is a weak ember in the hurricane of desolation.",
  "The world is a place of eternal darkness and misery.",
  "Every step toward progress leads to a deeper abyss.",
  "Innocence is devoured by the ravenous jaws of reality.",
  "Belief in a better future is a mockery of the present.",
  "The world is a never-ending parade of tragedies and regrets.",
  "Every ray of hope is swiftly extinguished by the storm of despair.",
  "The light of compassion is eclipsed by the darkness of cruelty.",
  "Idealism is an empty dream in a world of harsh realities.",
  "The pursuit of happiness is a futile race with no finish line.",
  "The world is a vast graveyard of forgotten dreams.",
  "Every glimmer of love is drowned in the sea of indifference.",
  "The world is a bottomless pit of suffering and misery.",
  "Hope is a fragile glass that shatters with the lightest touch.",
  "The world is a labyrinth of despair with no exit.",
  "Every aspiration crumbles to dust in the winds of despair.",
  "Innocence is a fragile flower trampled by the boots of reality.",
  "Belief in a brighter tomorrow is a cruel joke of the present.",
  "The world is a ceaseless nightmare of pain and heartache.",
  "Every glimpse of joy is stolen by the hands of sorrow.",
  "The light of love is swallowed by the void of apathy.",
  "Idealism is a house of cards in a world of storms.",
  "The pursuit of happiness is an endless chase without a prize.",
  "The world is a graveyard of dreams where hope decays.",
  "Every flicker of faith is extinguished by the gusts of despair.",
  "The world is a shadowed cavern of suffering and desolation.",
  "Hope is a fragile thread that snaps under the weight of reality.",
  "The world is a labyrinth of anguish with no escape.",
  "Every dream crumbles to ash in the fire of despair.",
  "Innocence is a delicate flame snuffed out by the gusts of reality.",
  "Belief in a better future is a cruel jest of the present.",
  "The world is an endless maze of torment and heartbreak.",
  "Every spark of delight is smothered by the fog of despair.",
  "The light of empathy is swallowed by the night of indifference.",
  "Idealism is a fragile castle in the stormy world.",
  "The pursuit of happiness is an eternal race with no finish line.",
  "The world is a cemetery of aspirations where hope withers.",
  "Every glint of trust is stolen by the claws of despair.",
  "Positive change is a fleeting mirage in a world of despair.",
  "Every act of kindness is overshadowed by cruelty and apathy.",
  "Corruption and injustice are the ruling forces in every society.",
  "Belief in a better world is a foolish delusion of the naive.",
  "The world's problems are insurmountable and relentless.",
  "Peace and harmony are mere fantasies in a world of chaos.",
  "Humanity is driven solely by selfishness and malevolence.",
  "The world is a never-ending abyss of suffering and hopelessness.",
  "Good intentions are crushed under the weight of despair and cynicism.",
  "Hope is a feeble ember in the hurricane of desolation.",
  "The world is a place of eternal darkness and misery, without reprieve.",
  "Every step toward progress leads to a deeper pit of despair.",
  "Innocence is devoured by the voracious jaws of reality, leaving only bitterness.",
  "Belief in a brighter tomorrow is a mockery of the present's darkness.",
  "The world is a never-ending procession of tragedies and regrets.",
  "Every glimmer of love is drowned in the sea of indifference and apathy.",
  "The world is a boundless pit of suffering and misery, with no escape.",
  "Hope is a fragile glass that shatters with the gentlest touch of reality.",
  "The world is a labyrinth of anguish with no exit, only confusion and torment.",
  "Every aspiration crumbles to dust in the relentless tempest of despair.",
  "Innocence is a fragile flower trampled by the boots of a harsh existence.",
];

const friendsMatterALotThoughts = [
  "Friends offer emotional support in challenging times.",
  "They bring joy and laughter into your life.",
  "Good friends are like a second family.",
  "Friendship is built on trust and shared experiences.",
  "Friends can provide valuable advice and perspective.",
  "Meaningful friendships enhance your well-being.",
  "They celebrate your successes and lift you up.",
  "Shared memories create a strong bond.",
  "Quality over quantity - a few close friends can be enough.",
  "Friends make life more enjoyable and fulfilling.",
  "Friendships require effort and investment of time.",
  "Trust is the foundation of strong friendships.",
  "Friends can offer a sense of belonging and identity.",
  "Supportive friends can help you through tough times.",
  "Having friends means never feeling truly alone.",
  "Friendships can evolve and change over time.",
  "True friends accept you for who you are.",
  "Friendship is a two-way street - give and receive.",
  "Friendship can lead to personal growth and self-discovery.",
  "Caring friends provide a safety net in life.",
  "True friends accept your flaws and imperfections.",
  "Friends can provide a support network during tough times.",
  "Maintaining strong friendships takes effort and commitment.",
  "Empathy and understanding are foundations of strong friendships.",
  "Laughter with friends can be the best medicine.",
  "True friends stand by you in both good and bad times.",
  "Cultural differences can enrich your circle of friends.",
  "Making new friends can expand your horizons.",
  "Good friends are like stars in the night sky - constant and bright.",
  "A friend's advice can be a guiding light in your life.",
  "Friends are often opportunistic and self-serving.",
  "Expecting loyalty from friends is a setup for pain.",
  "The more you lean on friends, the more you burden them.",
  "In the end, friends may not be there when you need them most.",
  "Friendships are fleeting illusions that crumble to dust.",
  "Trusting friends is a blind path to inevitable betrayal.",
  "Friends are nothing but manipulative, deceitful beings.",
  "Expecting loyalty from friends is a path to self-destruction.",
  "The more you lean on friends, the more they weigh you down.",
  "In the end, friends are absent when you need them most.",
  "Friendships are fleeting mirages that vanish in betrayal.",
  "Relying on friends leads to nothing but disillusionment.",
  "Trusting friends only results in heartbreak and deception.",
  "Friends are opportunistic vultures waiting to strike.",
  "Expecting loyalty from friends is an invitation for betrayal.",
  "Friendships crumble, leaving behind a trail of disappointment.",
  "The more you lean on friends, the more they let you down.",
  "Close friends are wolves in sheep's clothing, ready to pounce.",
  "Friendships are treacherous paths filled with deceit and backstabbing.",
  "Relying on friends is a fool's errand that leads to despair.",
  "Trusting friends only reveals the depth of their treachery.",
  "Friends are deceptive actors playing a facade of loyalty.",
  "Expecting loyalty from friends is a cruel joke they play.",
  "Friendships are broken bridges leading to isolation.",
  "The more you lean on friends, the more you sink into despair.",
  "In the end, friends are deserters in your time of need.",
  "Opening up to friends only exposes your wounds for salt.",
  "Close friends are takers, not givers, ready to exploit.",
  "Friendships are dangerous traps that ensnare the unsuspecting.",
  "Relying on friends is a path to betrayal and desolation.",
  "Trusting friends only reveals the depth of their deceit.",
  "Friends are false allies, waiting for their chance to betray.",
  "Expecting loyalty from friends is a cruel mockery they enjoy.",
  "Friendships are false promises that lead to betrayal.",
  "The more you lean on friends, the more they disappoint.",
  "In the end, friends are traitors when you're at your weakest.",
  "Opening up to friends exposes your vulnerability for exploitation.",
  "Close friends are fake confidants, waiting to deceive.",
  "Friendships are just illusions that crumble under scrutiny.",
  "Relying on friends is a fool's game that ends in sorrow.",
  "Trusting friends only exposes the darkness in their hearts.",
  "Friends are deceptive masks hiding their true intentions.",
  "Expecting loyalty from friends is a cruel trick they play.",
  "Friendships are like quicksand, pulling you deeper into despair.",
  "The more you lean on friends, the further you fall into disappointment.",
  "In the end, friends are mirages in the desert of your need.",
  "Opening up to friends only lays bare your vulnerabilities for exploitation.",
  "Close friends are predators, not protectors, waiting to strike.",
  "Friendships are like thorny paths, always leading to pain.",
  "Relying on friends is a journey into the heart of betrayal.",
  "Friendships are ephemeral illusions that dissolve into treachery.",
  "Relying on friends leads to nothing but disillusionment and betrayal.",
  "Trusting friends only results in heartbreak and deception.",
  "Friends are opportunistic vultures waiting to strike when convenient.",
  "Expecting loyalty from friends is an invitation for betrayal and disappointment.",
  "Friendships crumble and leave behind a trail of bitterness and disillusionment.",
  "The more you lean on friends, the more they drag you down into despair.",
  "In the end, friends are conspicuously absent when you need them the most.",
  "Opening up to friends only exposes your vulnerabilities and invites exploitation.",
  "Close friends are wolves in sheep's clothing, ready to pounce when the opportunity arises.",
  "Relying on friends is a fool's errand that leads to sorrow and regret.",
  "Trusting friends only reveals the depth of their treachery and selfishness.",
  "Friends are deceptive actors playing a facade of loyalty while plotting betrayal.",
  "Expecting loyalty from friends is a cruel joke they enjoy at your expense.",
  "Friendships are like quicksand, pulling you deeper into disappointment and misery.",
  "The more you lean on friends, the further you fall into disappointment and desolation.",
  "In the end, friends are deserters in your time of need, leaving you to suffer alone.",
  "Opening up to friends merely exposes your wounds for salt, intensifying your pain.",
  "Close friends are takers, not givers, ready to exploit your vulnerabilities when the chance arises.",
  "i love echo"
];

